# -*- coding: utf-8 -*-
"""Weather_predictor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IMzCaTJha2KyxamhF9rJ5f_lupYZbj1m
"""

from google.colab import drive

   drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

data = pd.read_csv("/content/drive/MyDrive/DailyDelhiClimateTrain.csv")
print(data.head())

print(data.describe())

print(data.info())

fig = px.line(data , x="date" , y="meantemp" ,title="Mean Temprature in delhi over the years ")
fig.show()

fig2 = px.line(data , x='date' , y='humidity',title = "Humidity in Delhi over years ")
fig2.show()

fig3 = px.scatter(data_frame= data ,x='humidity' , y='meantemp',size = 'meantemp' ,
                  trendline='ols', title ="Relationship between humidity and temperature ")
fig3.show()

fig3 = px.scatter(data_frame= data ,x='wind_speed' , y='meantemp',size = 'meantemp' ,
                  trendline='ols', title ="Relationship between wind speed and temperature ")
fig3.show()

data['date'] = pd.to_datetime(data['date'],format='%Y-%m-%d')
data['year'] = data['date'].dt.year
data['month'] = data['date'].dt.month
print(data.head())

plt.style.use('fivethirtyeight')
plt.figure(figsize=(15,10))
plt.title('Temperature change in dlehi over years')
sns.lineplot(data=data ,x='month',y=meante)

forecast_data = data.rename(columns = {'date':'ds' , 'meantemp':'y'})
print(forecast_data)

from prophet import Prophet
from prophet.plot import plot_plotly , plot_components_plotly

model = Prophet()
model.fit(forecast_data)
forecasts = model.make_future_dataframe(periods = 365)
predictions = model.predict(forecasts)
plot_plotly(model,predictions)
# plot_components_plotly(model,predictions)